name: Deploy to Pantheon
on:
  push:
    branches:
      - 'master'
      - 'fe-build'
      - 'sprint23'
      - 'test'
jobs:
  build:
    if: github.actor != 'Pantheon' && github.actor != 'Autopilot' && github.actor != 'Github Action'
    container:
      image: quay.io/pantheon-public/build-tools-ci:6.x
      options: --user root
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
    - name: Use Node.js 14.
      uses: actions/setup-node@v3
      with:
        node-version: 14.19.0

    # Cache vendor folder
    - name: Cache vendor folder
      uses: actions/cache@v2
      env:
        cache-name: cache-vendor
      with:
        path: ./vendor
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
    - name: node builder
      run: |
        cd wp-content/themes/understrap
        npm install jquery
        npm install
      # any other FE build commands here

    - name: Deployer (Git add,commit,push)
      env:
        pantheon_site: '${{ secrets.PANTHEON_SITE }}'
        pantheon_machine_token: '${{ secrets.PANTHEON_MACHINE_TOKEN }}'
      run: |
        git config --global user.email "gha@$pantheon_site"
        git config --global user.name "Github Action"
        # Authenticate with Terminus
        terminus -n auth:login --machine-token=$pantheon_machine_token
        # Push our bitbucket code to Pantheon
        echo "Github Actor: $GITHUB_ACTOR"
        echo "Deploying $pantheon_site to Pantheon $GITHUB_REF_NAME branch"
        if [ $GITHUB_REF_NAME = "master" ]
        then
          # Push to the dev environment
          echo "Pushing to Dev"
          terminus -n build:env:push $pantheon_site.dev --yes
        else
          # Create a new multidev environment (or push to an existing one)
          echo "Creating Multidev"
          terminus -n build:env:create $pantheon_site.dev "$GITHUB_REF_NAME" --yes
        fi